-- USE LojaIFSP3024865;
IIF DB_ID (N'LojaIFSP3024865') IS NULL 
    CREATE DATABASE LojaIFSP3024865;
ELSE 
    USE LojaIFSP3024865;
GO

-- Criação da Tabela
CREATE TABLE CLIENTES (
    ID INT PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Sexo CHAR(1) NULL,
    Idade  INT CHECK (Idade > 18 ) NOT NULL,
    CPF CHAR(11) UNIQUE NOT NULL,
    Email VARCHAR(200) DEFAULT 'meuemail@email.com' NOT NULL
    
);

ALTER TABLE CLIENTES
    ADD DDD CHAR(2) NULL,
     Telefone CHAR(10);
GO

